//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arduino
    {
        public int a_id { get; set; }
        public string a_value { get; set; }
        public int a_room_id { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
