//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BankAccount
    {
        public BankAccount()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ba_id { get; set; }
        [DisplayName("Número")]
        public string ba_number { get; set; }
        [DisplayName("Montante")]
        public Nullable<double> bar_cash { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
