//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChargeAccountReference
    {
        public ChargeAccountReference()
        {
            this.Users = new HashSet<User>();
        }
    
        public int car_id { get; set; }
        [DisplayName("Referência")]
        public string car_reference { get; set; }
        [DisplayName("Estado")]
        public int car_state { get; set; }
        [DisplayName("Validade")]
        public System.DateTime car_valtime { get; set; }
        [DisplayName("Montante")]
        public int car_amount { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
