//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCategory
    {
        public CourseCategory()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int cc_id { get; set; }
        public string cc_designation { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
