//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.Presences = new HashSet<Presence>();
            this.UserDisciplineLists = new HashSet<UserDisciplineList>();
        }
    
        public int d_id { get; set; }
        public string d_designation { get; set; }
        public Nullable<int> d_value { get; set; }
        public Nullable<int> d_yearcourse { get; set; }
        public Nullable<int> d_credits { get; set; }
        public int d_user_id { get; set; }
        public int d_course_id { get; set; }
        public int d_scontent_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ScheduleContent ScheduleContent { get; set; }
        public virtual ICollection<Presence> Presences { get; set; }
        public virtual ICollection<UserDisciplineList> UserDisciplineLists { get; set; }
    }
}
