//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public Presence()
        {
            this.UserPresenceLists = new HashSet<UserPresenceList>();
        }
    
        public int p_id { get; set; }
        public int p_discipline_id { get; set; }
        public int p_room_id { get; set; }
        public System.TimeSpan p_checkin { get; set; }
        public System.TimeSpan p_checkout { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<UserPresenceList> UserPresenceLists { get; set; }
    }
}
