//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        public Product()
        {
            this.PurchaseProductLists = new HashSet<PurchaseProductList>();
        }
    
        public int pr_id { get; set; }
        [DisplayName("Designação")]
        public string pr_designation { get; set; }
        [DisplayName("Preço")]
        public double pr_price { get; set; }
    
        public virtual ICollection<PurchaseProductList> PurchaseProductLists { get; set; }
    }
}
