//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseProductLists = new HashSet<PurchaseProductList>();
            this.UserPurchaseLists = new HashSet<UserPurchaseList>();
        }
    
        public int p_id { get; set; }
        [DisplayName("Nome da Compra (ID)")]
        public string p_designation { get; set; }
        [DisplayName("Total")]
        public Nullable<double> p_total { get; set; }
    
        public virtual ICollection<PurchaseProductList> PurchaseProductLists { get; set; }
        public virtual ICollection<UserPurchaseList> UserPurchaseLists { get; set; }
    }
}
