//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserDisciplineLists = new HashSet<UserDisciplineList>();
            this.UserPresenceLists = new HashSet<UserPresenceList>();
            this.UserPurchaseLists = new HashSet<UserPurchaseList>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int u_id { get; set; }
        public string u_name { get; set; }
        public int u_number { get; set; }
        public int u_course_id { get; set; }
        public int u_courseclass_id { get; set; }
        public int u_bankaccount_id { get; set; }
        public Nullable<int> u_chargeaccref_id { get; set; }
        public string u_password { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual ChargeAccountReference ChargeAccountReference { get; set; }
        public virtual Course Course { get; set; }
        public virtual CourseClass CourseClass { get; set; }
        public virtual ICollection<UserDisciplineList> UserDisciplineLists { get; set; }
        public virtual ICollection<UserPresenceList> UserPresenceLists { get; set; }
        public virtual ICollection<UserPurchaseList> UserPurchaseLists { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
