//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTGest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDisciplineList
    {
        public int udl_id { get; set; }
        public int udl_user_id { get; set; }
        public int udl_discipline_id { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual User User { get; set; }
    }
}
